import apiClient from "./ApiClient";

const unwrap = (value) => Array.isArray(value) ? value : Array.isArray(value?.data) ? value.data : [];

const cutinappService = {
  publicConfig: async () => (await apiClient.get("/cutinapp/config")).data,
  discoveryFacets: async () => (await apiClient.get("/cutinapp/discovery/facets")).data,
  locationStates: async () => (await apiClient.get("/cutinapp/locations/states")).data.states || [],
  locationCities: async (uf, q = "") => (await apiClient.get("/cutinapp/locations/cities", { params: { uf, q } })).data.cities || [],
  lookupCep: async (cep) => (await apiClient.get(`/cutinapp/locations/cep/${String(cep).replace(/\D/g, "")}`)).data.address,

  profileOverview: async () => (await apiClient.get("/cutinapp/profile/overview")).data,
  myProductions: async () => unwrap((await apiClient.get("/cutinapp/productions/mine")).data.productions),
  publicProductions: async (params = {}) => (await apiClient.get("/cutinapp/productions/public", { params })).data,
  getProduction: async (id) => (await apiClient.get(`/cutinapp/productions/${id}`)).data.production,
  publicProduction: async (slug) => (await apiClient.get(`/cutinapp/productions/public/${slug}`)).data,
  createProduction: async (formData) => (await apiClient.post("/cutinapp/productions", formData)).data,
  updateProduction: async (id, formData) => (await apiClient.post(`/cutinapp/productions/${id}`, formData)).data,
  artists: async (params = {}) => (await apiClient.get("/cutinapp/artists", { params })).data,
  publicArtist: async (slug) => (await apiClient.get(`/cutinapp/artists/${slug}`)).data,
  publicArtistMembers: async (slug) => (await apiClient.get(`/cutinapp/artists/${slug}/members`)).data,
  publicEventArtists: async (slug) => (await apiClient.get(`/cutinapp/events/public/${slug}/artists`)).data.artists || [],
  eventCommunity: async (slug, params = {}) => (await apiClient.get(`/cutinapp/events/public/${slug}/community`, { params })).data,
  createEventPost: async (eventId, payload) => (await apiClient.post(`/cutinapp/events/${eventId}/community`, payload)).data,
  deleteEventPost: async (postId) => (await apiClient.delete(`/cutinapp/community/${postId}`)).data,
  likeEventPost: async (postId) => (await apiClient.post(`/cutinapp/community/${postId}/like`)).data,
  unlikeEventPost: async (postId) => (await apiClient.delete(`/cutinapp/community/${postId}/like`)).data,
  rateEvent: async (eventId, rating) => (await apiClient.put(`/cutinapp/events/${eventId}/rating`, { rating })).data,
  reportEvent: async (eventId, payload) => (await apiClient.post(`/cutinapp/events/${eventId}/report`, payload)).data,
  moderationReports: async (params = {}) => (await apiClient.get("/cutinapp/moderation/reports", { params })).data,
  updateModerationReport: async (reportId, payload) => (await apiClient.put(`/cutinapp/moderation/reports/${reportId}`, payload)).data,
  myArtists: async () => unwrap((await apiClient.get("/cutinapp/artists/manageable", { params: { per_page: 100 } })).data.artists),
  createArtist: async (payload) => (await apiClient.post("/cutinapp/artists/provisional", payload)).data,
  updateArtist: async (id, payload) => (await apiClient.put(`/cutinapp/artists/${id}/managed`, payload)).data,
  updateArtistType: async (id, artistType) => (await apiClient.put(`/cutinapp/artists/${id}/type`, { artist_type: artistType })).data,
  artistMembers: async (id) => (await apiClient.get(`/cutinapp/artists/${id}/members`)).data.members || [],
  createArtistMember: async (id, payload) => (await apiClient.post(`/cutinapp/artists/${id}/members`, payload)).data,
  updateArtistMember: async (id, memberId, payload) => (await apiClient.put(`/cutinapp/artists/${id}/members/${memberId}`, payload)).data,
  deleteArtistMember: async (id, memberId) => (await apiClient.delete(`/cutinapp/artists/${id}/members/${memberId}`)).data,
  artistClaimability: async (eventId, artistId) => (await apiClient.get(`/cutinapp/events/${eventId}/artists/${artistId}/claim`)).data,
  claimArtistEvent: async (eventId, artistId, payload = {}) => (await apiClient.post(`/cutinapp/events/${eventId}/artists/${artistId}/claim`, payload)).data,
  myArtistClaims: async () => (await apiClient.get("/cutinapp/artist-claims/mine")).data,
  eventArtistClaims: async (eventId) => (await apiClient.get(`/cutinapp/events/${eventId}/artist-claims`)).data,
  reviewArtistClaim: async (eventId, claimId, payload) => (await apiClient.put(`/cutinapp/events/${eventId}/artist-claims/${claimId}`, payload)).data,
  eventArtists: async (eventId) => (await apiClient.get(`/cutinapp/events/${eventId}/artists`)).data,
  attachArtist: async (eventId, payload) => (await apiClient.post(`/cutinapp/events/${eventId}/artists`, payload)).data,
  detachArtist: async (eventId, artistId) => (await apiClient.delete(`/cutinapp/events/${eventId}/artists/${artistId}`)).data,
  follow: async (targetType, targetId) => (await apiClient.post("/cutinapp/follow", { target_type: targetType, target_id: targetId })).data,
  unfollow: async (targetType, targetId) => (await apiClient.delete("/cutinapp/follow", { data: { target_type: targetType, target_id: targetId } })).data,
  preferences: async () => (await apiClient.get("/cutinapp/preferences")).data.preferences,
  savePreferences: async (payload) => (await apiClient.put("/cutinapp/preferences", payload)).data,
  engagement: async (eventId, payload) => (await apiClient.put(`/cutinapp/events/${eventId}/engagement`, payload)).data,
  feed: async (params = {}) => (await apiClient.get("/cutinapp/feed", { params })).data,
  notifications: async (params = {}) => (await apiClient.get("/cutinapp/notifications", { params })).data,
  markNotificationRead: async (notificationId) => (await apiClient.post(`/cutinapp/notifications/${notificationId}/read`)).data,
  markAllNotificationsRead: async () => (await apiClient.post("/cutinapp/notifications/read-all")).data,
  publishEvent: async (eventId) => (await apiClient.post(`/cutinapp/events/${eventId}/publish`)).data,
  unpublishEvent: async (eventId) => (await apiClient.post(`/cutinapp/events/${eventId}/unpublish`)).data,
  eventCourtesies: async (eventId) => (await apiClient.get(`/cutinapp/events/${eventId}/courtesies`)).data,
  updateCourtesy: async (ticketId, payload) => (await apiClient.post(`/cutinapp/courtesies/${ticketId}`, payload)).data,
  deleteCourtesy: async (ticketId) => (await apiClient.delete(`/cutinapp/courtesies/${ticketId}`)).data,
  claimCourtesy: async (ticketId) => (await apiClient.post(`/cutinapp/passes/claim/${ticketId}`)).data,
  myPasses: async () => unwrap((await apiClient.get("/cutinapp/passes/mine")).data.passes),
  getPass: async (passId) => (await apiClient.get(`/cutinapp/passes/${passId}`)).data.pass,
  eventParticipants: async (eventId) => (await apiClient.get(`/cutinapp/events/${eventId}/participants`)).data,
  checkIn: async (token, eventId) => (await apiClient.post("/cutinapp/checkin", { token, event_id: Number(eventId) })).data,
  checkInStats: async (eventId) => (await apiClient.get(`/cutinapp/checkin/event/${eventId}/stats`)).data,
};

export default cutinappService;
