import React, { useMemo, useState } from "react";
import { Button, Form } from "react-bootstrap";
import { Link, useNavigate } from "react-router-dom";
import AuthPageShell from "../../components/auth/AuthPageShell";
import ProcessingIndicatorComponent from "../../components/ProcessingIndicatorComponent";
import authService from "../../services/AuthService";

export default function PasswordEmailPage() {
  const navigate = useNavigate();
  const [step,setStep]=useState("email"),[email,setEmail]=useState(""),[code,setCode]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const passwordOk=useMemo(()=>password.length>=8&&/[a-z]/.test(password)&&/[A-Z]/.test(password)&&/\d/.test(password)&&/[^A-Za-z0-9]/.test(password),[password]);
  const request=async(e)=>{e.preventDefault();setLoading(true);setError("");setMessage("");try{const r=await authService.passwordEmail(email.trim().toLowerCase());setMessage(r?.message||"Código enviado.");setStep("reset");}catch(err){setError(err?.message||"Não foi possível enviar o código.");}finally{setLoading(false);}};
  const reset=async(e)=>{e.preventDefault();if(!passwordOk||password!==confirm)return;setLoading(true);setError("");setMessage("");try{const r=await authService.passwordReset(email.trim().toLowerCase(),code,password,confirm);setMessage(r?.message||"Senha redefinida com sucesso.");window.setTimeout(()=>navigate("/login",{replace:true}),800);}catch(err){setError(err?.message||"Não foi possível redefinir a senha.");}finally{setLoading(false);}};
  return <AuthPageShell title="Recuperar acesso" subtitle={step==="email"?"Informe seu e-mail para receber um código de recuperação.":"Use o código recebido e defina uma nova senha."} compact>{loading&&<ProcessingIndicatorComponent label={step==="email"?"Enviando código":"Redefinindo senha"}/>}<Form onSubmit={step==="email"?request:reset} className="cut-auth-form">{error&&<div className="cut-form-message cut-form-message--error">{error}</div>}{message&&<div className="cut-form-message cut-form-message--success">{message}</div>}{step==="email"?<Form.Group><Form.Label>E-mail</Form.Label><Form.Control type="email" value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="email" placeholder="seu@email.com"/></Form.Group>:<><Form.Group><Form.Label>Código recebido</Form.Label><Form.Control value={code} onChange={(e)=>setCode(e.target.value)} autoComplete="one-time-code"/></Form.Group><Form.Group><Form.Label>Nova senha</Form.Label><Form.Control type="password" value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="new-password"/><Form.Text>8+ caracteres com maiúscula, minúscula, número e símbolo.</Form.Text></Form.Group><Form.Group><Form.Label>Confirmar senha</Form.Label><Form.Control type="password" value={confirm} onChange={(e)=>setConfirm(e.target.value)} autoComplete="new-password"/></Form.Group></>}<Button type="submit" className="cut-primary-action" disabled={loading||(step==="email"?!email.trim():!code.trim()||!passwordOk||password!==confirm)}>{step==="email"?"Enviar código":"Salvar nova senha"}</Button>{step==="reset"&&<Button type="button" variant="outline-light" onClick={()=>setStep("email")}>Solicitar outro código</Button>}<div className="cut-auth-inline-links"><Link to="/login">Voltar ao login</Link><span>•</span><Link to="/register">Criar conta</Link></div></Form></AuthPageShell>;
}
