import React,{useState}from"react";
import{Link,useNavigate}from"react-router-dom";
import authService from"../../services/AuthService";
import CutinLayout from"../../components/CutinLayout";
import"../CutinPages.css";

export default function RegisterPage(){
 const navigate=useNavigate();const[form,setForm]=useState({first_name:"",email:"",password:"",confirm:""});const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));
 const submit=async e=>{e.preventDefault();setError("");if(form.password!==form.confirm){setError("As senhas não conferem.");return}if(form.password.length<8){setError("A senha precisa ter pelo menos 8 caracteres, com maiúscula, minúscula, número e símbolo.");return}setLoading(true);try{await authService.register({first_name:form.first_name,email:form.email,password:form.password});navigate("/email-verify",{replace:true})}catch(x){if(x&&typeof x==="object"&&!(x instanceof Error)){setError(Object.values(x).flat().join(" "))}else setError(x?.message||"Não foi possível criar a conta.")}finally{setLoading(false)}};
 return <CutinLayout><section className="cutin-auth-wrap"><div className="auth-copy"><span className="eyebrow">Faça parte da experiência</span><h1>Crie sua conta.</h1><p>Uma única conta para comprar ingressos, produzir eventos, trabalhar em equipes e acompanhar comissões na Cutinapp.</p></div><div className="panel auth-card"><div className="cutin-auth-logo">C</div><h2>Criar conta</h2><p className="muted">O e-mail será validado por código após o cadastro.</p><form onSubmit={submit}><label className="cutin-field"><span>Nome</span><input name="first_name" value={form.first_name} onChange={change} autoComplete="name" required/></label><label className="cutin-field"><span>E-mail</span><input name="email" type="email" value={form.email} onChange={change} autoComplete="email" required/></label><label className="cutin-field"><span>Senha</span><input name="password" type="password" value={form.password} onChange={change} autoComplete="new-password" required/></label><label className="cutin-field"><span>Confirmar senha</span><input name="confirm" type="password" value={form.confirm} onChange={change} autoComplete="new-password" required/></label><small className="muted">Use maiúscula, minúscula, número e símbolo.</small>{error&&<div className="error-box">{error}</div>}<button className="primary auth-submit" disabled={loading}>{loading?"Criando conta...":"Criar conta"}</button></form><div className="auth-links"><span>Já tem conta? <Link to="/login">Entrar</Link></span></div></div></section></CutinLayout>
}
