import React, { useEffect, useState } from "react";
import { Alert, Badge, Button, Card, Col, Container, Row } from "react-bootstrap";
import { useNavigate } from "react-router-dom";
import NavlogComponent from "../../components/NavlogComponent";
import ProcessingIndicatorComponent from "../../components/ProcessingIndicatorComponent";
import eventService from "../../services/EventService";

const formatDate=(value)=>value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Data não informada";
export default function EventManagePage(){const navigate=useNavigate();const[events,setEvents]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{let active=true;eventService.myEvents().then(i=>active&&setEvents(i)).catch(e=>active&&setError(e?.message||"Não foi possível carregar seus eventos.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);return <div className="cut-app-page"><NavlogComponent/>{loading&&<ProcessingIndicatorComponent label="Carregando eventos"/>}<Container className="cut-page-container py-4 py-lg-5"><div className="cut-page-heading"><div><span className="cut-eyebrow">Área do produtor</span><h1>Meus eventos</h1><p>Edite informações, controle publicação, crie cortesias, acompanhe participantes e opere a portaria.</p></div><Button onClick={()=>navigate("/event/create")}><i className="fa-solid fa-plus me-2"/>Novo evento</Button></div>{error&&<Alert variant="danger">{error}</Alert>}{!loading&&events.length===0?<Card className="cut-empty-state"><Card.Body><h2>Nenhum evento criado</h2><p>Crie sua produção e publique seu primeiro evento.</p><Button onClick={()=>navigate("/event/create")}>Criar evento</Button></Card.Body></Card>:<Row className="g-4">{events.map(event=><Col lg={6} key={event.id}><Card className="cut-panel h-100"><Card.Body className="p-4"><div className="d-flex justify-content-between gap-3 align-items-start"><div><span className="cut-eyebrow">{event.production?.name||"Produção"}</span><h2 className="cut-section-title mt-2 mb-1">{event.title}</h2></div><Badge bg={event.is_cancelled?"danger":event.is_published?"success":"secondary"}>{event.is_cancelled?"Cancelado":event.is_published?"Publicado":"Rascunho"}</Badge></div><p className="mb-1">{formatDate(event.start_date)}</p><p className="text-secondary">{event.venue||event.address}</p><div className="cut-card-actions mt-4"><Button onClick={()=>navigate(`/event/edit/${event.id}`)}>Editar</Button><Button variant="outline-light" onClick={()=>navigate(`/ticket/create?eventId=${event.id}`)}>Cortesia</Button><Button variant="outline-light" onClick={()=>navigate(`/event/${event.id}/participants`)}>Participantes</Button><Button variant="outline-light" onClick={()=>navigate("/checkin")}>Portaria</Button>{event.slug&&<Button variant="outline-light" onClick={()=>navigate(`/event/${event.slug}`)}>Página pública</Button>}</div></Card.Body></Card></Col>)}</Row>}</Container></div>}
