import React,{useEffect,useState}from"react";
import{Link,useParams}from"react-router-dom";
import CutinLayout from"../components/CutinLayout";
import CutinService from"../services/CutinService";
import"./CutinPages.css";

const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));
const errMsg=e=>e?.response?.data?.message||e?.response?.data?.error||Object.values(e?.response?.data?.errors||{}).flat()[0]||"Não foi possível concluir a operação.";

export default function CutinTicketLotsPage(){
 const{id}=useParams();const[tickets,setTickets]=useState([]);const[error,setError]=useState("");const[editing,setEditing]=useState(null);const[form,setForm]=useState({name:"",ticket_type:"Inteira",price:"",quantity:"",limit_date:"",description:""});
 const load=()=>CutinService.ticketsByEvent(id).then(v=>setTickets(Array.isArray(v)?v:[])).catch(e=>setError(errMsg(e)));
 useEffect(()=>{load()},[id]);
 const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));
 const reset=()=>{setEditing(null);setForm({name:"",ticket_type:"Inteira",price:"",quantity:"",limit_date:"",description:""})};
 const submit=async e=>{e.preventDefault();setError("");try{const payload={event_id:Number(id),name:form.name,ticket_type:form.ticket_type,type:"event",price:Number(form.price),quantity:Number(form.quantity),limit_date:form.limit_date||null,description:form.description||null};if(editing)await CutinService.updateTicket(editing,payload);else await CutinService.createTicket(payload);reset();await load()}catch(x){setError(errMsg(x))}};
 const edit=t=>{setEditing(t.id);setForm({name:t.name||"",ticket_type:t.ticket_type||"Inteira",price:String(t.price??""),quantity:String(t.quantity??""),limit_date:t.limit_date?String(t.limit_date).slice(0,16):"",description:t.description||""});window.scrollTo({top:0,behavior:"smooth"})};
 return <CutinLayout><section className="cutin-section"><div className="section-head"><div><span className="eyebrow">Ingressos</span><h1>Lotes do evento</h1><p className="page-subtitle">Crie lotes, defina preço, quantidade e data limite. O checkout respeita disponibilidade e encerra lotes vencidos.</p></div><Link className="secondary" to={`/gerenciar/evento/${id}`}>Voltar à gestão</Link></div>{error&&<div className="error-box">{error}</div>}<div className="two-col"><div className="panel"><h3>{editing?"Editar lote":"Novo lote"}</h3><form className="form-grid" onSubmit={submit}><input name="name" value={form.name} onChange={change} placeholder="Ex.: 1º lote" required/><select name="ticket_type" value={form.ticket_type} onChange={change}><option>Inteira</option><option>Meia</option><option>VIP</option><option>Cortesia</option><option>Promocional</option></select><input name="price" value={form.price} onChange={change} type="number" min="0" step="0.01" placeholder="Preço" required/><input name="quantity" value={form.quantity} onChange={change} type="number" min="0" step="1" placeholder="Quantidade disponível" required/><label className="cutin-field"><span>Encerramento do lote</span><input name="limit_date" value={form.limit_date} onChange={change} type="datetime-local"/></label><textarea name="description" value={form.description} onChange={change} placeholder="Descrição e regras do lote" rows="5"/><div className="inline-actions"><button className="primary">{editing?"Salvar lote":"Criar lote"}</button>{editing&&<button type="button" className="secondary" onClick={reset}>Cancelar</button>}</div></form></div><div className="panel"><h3>Lotes cadastrados</h3>{tickets.length?tickets.map(t=><div className="lot-row" key={t.id}><div><strong>{t.name}</strong><small>{t.ticket_type} · {money(t.price)} · {t.quantity} disponíveis</small>{t.limit_date&&<small>até {new Date(t.limit_date).toLocaleString("pt-BR")}</small>}</div><div className="inline-actions"><button onClick={()=>edit(t)}>Editar</button><button className="danger-button" onClick={async()=>{if(!window.confirm(`Excluir o lote ${t.name}?`))return;try{await CutinService.deleteTicket(t.id);load()}catch(x){setError(errMsg(x))}}}>Excluir</button></div></div>):<p className="muted">Nenhum lote criado.</p>}</div></div></section></CutinLayout>
}
