import React,{useEffect,useState}from"react";
import CutinLayout from"../components/CutinLayout";
import CutinService from"../services/CutinService";
import"./CutinPages.css";

const Page=({title,subtitle,children})=><CutinLayout><section className="cutin-section"><span className="eyebrow">Cutinapp</span><h1 style={{fontSize:"clamp(2.4rem,6vw,4.8rem)",margin:"10px 0"}}>{title}</h1><p style={{color:"var(--cutin-muted)",maxWidth:760}}>{subtitle}</p>{children}</section></CutinLayout>;

export function EventsHubPage(){const[events,setEvents]=useState([]);const[city,setCity]=useState("");useEffect(()=>{CutinService.events(city?{city}:{}).then(v=>setEvents(Array.isArray(v)?v:[])).catch(()=>setEvents([]))},[city]);return <Page title="Eventos" subtitle="Descubra o que está acontecendo e encontre a próxima experiência para viver."><div className="panel"><label>Cidade</label><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Digite sua cidade" style={{width:"100%",marginTop:8,padding:14,borderRadius:12,border:"1px solid var(--cutin-line)",background:"var(--cutin-bg)",color:"var(--cutin-text)"}}/></div><div className="event-grid" style={{marginTop:18}}>{events.map((e,i)=><article className="event-card" key={e.id||i}><div className="event-cover"><span>{e.city||"Evento"}</span></div><div className="event-body"><h3>{e.name||e.title}</h3><p>{e.description||"Confira detalhes, ingressos e produtos."}</p></div></article>)}</div></Page>}

export function ProducerDashboardPage(){const[events,setEvents]=useState([]);useEffect(()=>{CutinService.myEvents().then(v=>setEvents(Array.isArray(v)?v:[])).catch(()=>setEvents([]))},[]);return <Page title="Central do produtor" subtitle="Sua operação de eventos: publicação, vendas, lotes, produtos, equipe e desempenho."><div className="dashboard-grid"><div className="metric"><span>Eventos</span><strong>{events.length}</strong></div><div className="metric"><span>Vendas</span><strong>—</strong></div><div className="metric"><span>Ingressos emitidos</span><strong>—</strong></div><div className="metric"><span>Comissões</span><strong>—</strong></div></div><div className="panel"><h3>Meus eventos</h3>{events.length?<table><thead><tr><th>Evento</th><th>Status</th><th>Data</th></tr></thead><tbody>{events.map((e,i)=><tr key={e.id||i}><td>{e.name||e.title}</td><td>{e.status||"ativo"}</td><td>{e.date||e.start_at||"—"}</td></tr>)}</tbody></table>:<p style={{color:"var(--cutin-muted)"}}>Nenhum evento encontrado. O primeiro passo é cadastrar sua produção e publicar um evento.</p>}</div></Page>}

export function TicketsPage(){const[tickets,setTickets]=useState([]);useEffect(()=>{CutinService.myTickets().then(v=>setTickets(Array.isArray(v)?v:[])).catch(()=>setTickets([]))},[]);return <Page title="Meus ingressos" subtitle="Seus acessos ficam organizados aqui para consulta e validação no evento."><div className="panel">{tickets.length?tickets.map((t,i)=><div key={t.id||i} style={{padding:14,borderBottom:"1px solid var(--cutin-line)"}}><strong>{t.event?.name||t.name||"Ingresso"}</strong><p style={{color:"var(--cutin-muted)"}}>{t.code||t.status||"Emitido"}</p></div>):<p style={{color:"var(--cutin-muted)"}}>Você ainda não possui ingressos.</p>}</div></Page>}

export function MarketplacePage(){return <Page title="Produtos & experiências" subtitle="Produtos, combos, consumação e experiências que podem ser adquiridos antes do evento."><div className="feature-grid"><article><b>Pré-venda</b><h3>Produtos do evento</h3><p>Venda camisetas, copos, kits e outros itens antecipadamente.</p></article><article><b>Experiências</b><h3>Upsell inteligente</h3><p>Área VIP, estacionamento, consumação e experiências adicionais.</p></article><article><b>Operação</b><h3>Retirada organizada</h3><p>Pedidos ligados ao participante e ao evento para facilitar a entrega.</p></article></div></Page>}

export function TeamPage(){return <Page title="Equipe & parceiros" subtitle="Organize promoters, fornecedores e colaboradores que participam da operação de cada evento."><div className="feature-grid"><article><b>Promoters</b><h3>Comissão rastreável</h3><p>Cada promoter terá vínculo, código/link de venda e regras de comissão.</p></article><article><b>Fornecedores</b><h3>Parceiros do evento</h3><p>Cadastre fornecedores, responsabilidades, contatos e situação contratual.</p></article><article><b>Colaboradores</b><h3>Funções e acesso</h3><p>Defina funções operacionais e permissões específicas por evento.</p></article></div></Page>}
