import React,{useEffect,useMemo,useRef,useState}from"react";
import{Link,useParams}from"react-router-dom";
import{QRCodeSVG}from"qrcode.react";
import CutinLayout from"../components/CutinLayout";
import CutinService from"../services/CutinService";
import"./CutinPages.css";

const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));
const date=v=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const Field=({label,...props})=><label className="cutin-field"><span>{label}</span><input {...props}/></label>;
const apiError=(err,fallback)=>err?.response?.data?.message||Object.values(err?.response?.data?.errors||{}).flat()[0]||fallback;

export function PublicEventPage(){
 const{id}=useParams();
 const[payload,setPayload]=useState(null);const[error,setError]=useState("");const[cart,setCart]=useState({});const[result,setResult]=useState(null);const[pix,setPix]=useState(null);const[paying,setPaying]=useState(false);
 const[form,setForm]=useState({buyer_name:"",buyer_email:"",buyer_document:"",buyer_phone:"",payment_method:"pix",promoter_code:new URLSearchParams(window.location.search).get("ref")||"",promotion_code:""});
 useEffect(()=>{CutinService.publicEvent(id).then(setPayload).catch(e=>setError(apiError(e,"Evento não encontrado.")))},[id]);
 useEffect(()=>{if(!result?.sale?.public_id||result?.sale?.payment_status==="paid"||!pix)return;const timer=setInterval(async()=>{try{const r=await CutinService.paymentStatus(result.sale.public_id);if(r?.sale?.payment_status==="paid"){setResult(v=>({...v,sale:r.sale,message:"Pagamento confirmado. Seus ingressos já foram emitidos."}));clearInterval(timer)}}catch{}},5000);return()=>clearInterval(timer)},[result?.sale?.public_id,result?.sale?.payment_status,pix]);
 const lines=useMemo(()=>{if(!payload)return[];const all=[...(payload.tickets||[]).map(x=>({...x,type:"ticket"})),...(payload.products||[]).map(x=>({...x,type:"product"}))];return all.filter(x=>(cart[`${x.type}-${x.id}`]||0)>0).map(x=>({...x,quantity:cart[`${x.type}-${x.id}`]}))},[payload,cart]);
 const subtotal=lines.reduce((s,x)=>s+Number(x.price||0)*x.quantity,0);
 const add=(type,id,d=1)=>setCart(c=>({...c,[`${type}-${id}`]:Math.max(0,(c[`${type}-${id}`]||0)+d)}));
 const checkout=async e=>{e.preventDefault();setError("");setPaying(true);try{const r=await CutinService.checkout(id,{...form,items:lines.map(x=>({type:x.type,id:x.id,quantity:x.quantity}))});setResult(r);if(r?.sale?.payment_status!=="paid"&&r?.sale?.public_id&&Number(r.sale.total)>0){const p=await CutinService.createPix(r.sale.public_id);setPix(p.pix)}}catch(err){setError(apiError(err,"Não foi possível concluir a compra."))}finally{setPaying(false)}};
 const copy=async value=>{try{await navigator.clipboard.writeText(value)}catch{}};
 if(error&&!payload)return <CutinLayout><section className="cutin-section"><div className="empty-card">{error}</div></section></CutinLayout>;
 if(!payload)return <CutinLayout><section className="cutin-section"><div className="empty-card">Carregando evento...</div></section></CutinLayout>;
 const e=payload.event;
 return <CutinLayout><section className="cutin-section"><div className="event-detail-hero"><div><span className="eyebrow">{e.city||"Evento"}</span><h1>{e.title}</h1><p>{e.description}</p><div className="event-meta"><span>{date(e.start_date)}</span><span>{e.venue||e.address}</span><span>{e.production?.name||e.organizer_name||"Cutinapp"}</span></div></div></div>
 <div className="two-col"><div><h2>Ingressos</h2><div className="stack">{(payload.tickets||[]).map(t=><article className="panel" key={t.id}><div className="row-between"><div><strong>{t.name}</strong><p>{t.description}</p><small>{t.quantity} disponíveis</small></div><b>{money(t.price)}</b></div><div className="qty"><button onClick={()=>add("ticket",t.id,-1)}>−</button><span>{cart[`ticket-${t.id}`]||0}</span><button onClick={()=>add("ticket",t.id,1)} disabled={Number(t.quantity)<=Number(cart[`ticket-${t.id}`]||0)}>+</button></div></article>)}</div>
 <h2>Produtos & extras</h2><div className="stack">{(payload.products||[]).length?(payload.products||[]).map(p=><article className="panel" key={p.id}><div className="row-between"><div><strong>{p.name}</strong><p>{p.description}</p>{p.stock!==null&&<small>{p.stock} em estoque</small>}</div><b>{money(p.price)}</b></div><div className="qty"><button onClick={()=>add("product",p.id,-1)}>−</button><span>{cart[`product-${p.id}`]||0}</span><button onClick={()=>add("product",p.id,1)} disabled={p.stock!==null&&Number(p.stock)<=Number(cart[`product-${p.id}`]||0)}>+</button></div></article>):<div className="empty-card">Este evento ainda não publicou produtos extras.</div>}</div></div>
 <aside className="panel checkout-box"><h2>Seu pedido</h2>{lines.length?lines.map(x=><div className="row-between compact" key={`${x.type}-${x.id}`}><span>{x.quantity}× {x.name}</span><b>{money(Number(x.price)*x.quantity)}</b></div>):<p className="muted">Nenhum item selecionado.</p>}<hr/><div className="row-between compact"><strong>Subtotal</strong><strong>{money(subtotal)}</strong></div>
 {result?<div>{result.sale?.payment_status==="paid"?<div className="success-box"><strong>Pagamento confirmado</strong><p>Pedido {result.sale.public_id}</p><Link to="/meus-ingressos">Abrir meus ingressos</Link></div>:pix?<div className="pix-box"><span className="eyebrow">PIX</span><h3>Pague para emitir seus ingressos</h3>{pix.qr_image?<img className="pix-qr" src={pix.qr_image} alt="QR Code PIX"/>:<QRCodeSVG value={pix.pix_copy_paste||""} size={210}/>}<textarea value={pix.pix_copy_paste||""} readOnly/><button className="secondary" onClick={()=>copy(pix.pix_copy_paste)}>Copiar PIX copia e cola</button>{pix.payment_link&&<a className="primary" href={pix.payment_link} target="_blank" rel="noreferrer">Abrir pagamento</a>}<p className="muted">A confirmação é automática. Esta tela verifica o pagamento periodicamente.</p></div>:<div className="empty-card">Gerando cobrança PIX...</div>}</div>:<form onSubmit={checkout}><Field label="Nome completo" value={form.buyer_name} onChange={x=>setForm({...form,buyer_name:x.target.value})} required/><Field label="E-mail" type="email" value={form.buyer_email} onChange={x=>setForm({...form,buyer_email:x.target.value})} required/><Field label="CPF/CNPJ (opcional)" value={form.buyer_document} onChange={x=>setForm({...form,buyer_document:x.target.value})}/><Field label="Telefone" value={form.buyer_phone} onChange={x=>setForm({...form,buyer_phone:x.target.value})}/><Field label="Cupom" value={form.promotion_code} onChange={x=>setForm({...form,promotion_code:x.target.value.toUpperCase()})}/><Field label="Código do promoter" value={form.promoter_code} onChange={x=>setForm({...form,promoter_code:x.target.value.toUpperCase()})}/><div className="payment-choice"><b>Pagamento online</b><span>PIX · confirmação automática</span></div>{error&&<p className="error-text">{error}</p>}<button className="primary" disabled={!lines.length||paying}>{paying?"Gerando pedido...":"Finalizar com PIX"}</button></form>}</aside></div></section></CutinLayout>
}

export function EventManagePage(){
 const{id}=useParams();const[d,setD]=useState(null);const[members,setMembers]=useState([]);const[promoters,setPromoters]=useState([]);const[promotions,setPromotions]=useState([]);const[tab,setTab]=useState("dashboard");const[msg,setMsg]=useState("");
 const load=()=>Promise.all([CutinService.dashboard(id),CutinService.members(id),CutinService.promoters(id),CutinService.promotions(id)]).then(([a,b,c,p])=>{setD(a);setMembers(Array.isArray(b)?b:[]);setPromoters(Array.isArray(c)?c:[]);setPromotions(Array.isArray(p)?p:[])}).catch(e=>setMsg(apiError(e,"Não foi possível carregar a gestão."));
 useEffect(()=>{load()},[id]);
 const addMember=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget);await CutinService.createMember(id,Object.fromEntries(f));e.currentTarget.reset();await load()}catch(x){setMsg(apiError(x,"Não foi possível adicionar a pessoa."))}};
 const addPromo=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget);await CutinService.createPromotion(id,{...Object.fromEntries(f),discount_value:Number(f.get("discount_value"))});e.currentTarget.reset();await load()}catch(x){setMsg(apiError(x,"Não foi possível criar a promoção."))}};
 const addPromoter=async memberId=>{try{await CutinService.createPromoter(id,{member_id:memberId,commission_type:"percentage",commission_value:10});await load()}catch(x){setMsg(apiError(x,"Não foi possível ativar o promoter."))}};
 if(!d)return <CutinLayout><section className="cutin-section"><div className="empty-card">{msg||"Carregando gestão..."}</div></section></CutinLayout>;
 const m=d.metrics||{};
 return <CutinLayout><section className="cutin-section"><div className="section-head"><div><span className="eyebrow">Gestão do evento</span><h1>{d.event?.title}</h1></div><div className="hero-actions"><Link className="secondary" to={`/event/update/${id}`}>Editar evento</Link><Link className="secondary" to={`/event/${id}/items`}>Produtos</Link><Link className="primary" to={`/evento/${id}`}>Página pública</Link></div></div>{msg&&<div className="error-box">{msg}</div>}<div className="tabs">{["dashboard","equipe","promoters","promocoes","vendas"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
 {tab==="dashboard"&&<><div className="dashboard-grid"><div className="metric"><span>Vendas</span><strong>{m.sales_count||0}</strong></div><div className="metric"><span>Receita</span><strong>{money(m.revenue)}</strong></div><div className="metric"><span>Ingressos</span><strong>{m.tickets_issued||0}</strong></div><div className="metric"><span>Check-ins</span><strong>{m.checkins||0}</strong></div><div className="metric"><span>Comissões</span><strong>{money(m.commissions)}</strong></div><div className="metric"><span>Equipe</span><strong>{m.members||0}</strong></div></div><div className="panel"><h3>Ranking de promoters</h3>{(d.promoter_ranking||[]).length?(d.promoter_ranking||[]).map(p=><div className="row-between" key={p.id}><span>{p.code} · {p.sales_count} vendas</span><b>{money(p.revenue)} · {money(p.commissions)} comissão</b></div>):<p className="muted">Ainda não há vendas atribuídas a promoters.</p>}</div></>}
 {tab==="equipe"&&<div className="two-col"><div className="panel"><h3>Adicionar pessoa</h3><form onSubmit={addMember} className="form-grid"><input name="name" placeholder="Nome" required/><input name="email" type="email" placeholder="E-mail"/><input name="phone" placeholder="Telefone"/><select name="role" defaultValue="collaborator"><option value="manager">Gerente</option><option value="promoter">Promoter</option><option value="supplier">Fornecedor</option><option value="collaborator">Colaborador</option><option value="checker">Operador de check-in</option></select><button className="primary">Adicionar</button></form></div><div className="panel"><h3>Equipe atual</h3>{members.map(x=><div className="row-between" key={x.id}><span><b>{x.name}</b><small>{x.role} · {x.status}<br/>{x.email}</small></span><div className="inline-actions">{x.role==="promoter"&&!promoters.some(p=>Number(p.member_id)===Number(x.id))&&<button onClick={()=>addPromoter(x.id)}>Ativar comissão</button>}<button className="danger-button" onClick={async()=>{await CutinService.deleteMember(id,x.id);load()}}>Remover</button></div></div>)}</div></div>}
 {tab==="promoters"&&<div className="panel"><h3>Promoters e links rastreáveis</h3>{promoters.length?promoters.map(p=><div className="row-between" key={p.id}><span><b>{p.name||p.code}</b><small>Código {p.code} · {p.commission_type==="percentage"?`${p.commission_value}%`:money(p.commission_value)}</small></span><div className="inline-actions"><button onClick={()=>navigator.clipboard?.writeText(`${window.location.origin}/evento/${id}?ref=${p.code}`)}>Copiar link</button><button onClick={async()=>{await CutinService.updatePromoter(id,p.id,{active:!p.active});load()}}>{p.active?"Pausar":"Ativar"}</button></div></div>):<p className="muted">Cadastre uma pessoa com função promoter e ative sua comissão.</p>}</div>}
 {tab==="promocoes"&&<div className="two-col"><div className="panel"><h3>Criar promoção</h3><form onSubmit={addPromo} className="form-grid"><input name="name" placeholder="Nome da promoção" required/><input name="code" placeholder="Cupom (opcional)"/><select name="discount_type"><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select><input name="discount_value" type="number" step="0.01" min="0" placeholder="Desconto" required/><input name="usage_limit" type="number" min="1" placeholder="Limite de usos (opcional)"/><button className="primary">Criar promoção</button></form></div><div className="panel"><h3>Promoções</h3>{promotions.map(p=><div className="row-between" key={p.id}><span>{p.name}<small>{p.code||"sem cupom"} · {p.used_count||0}{p.usage_limit?`/${p.usage_limit}`:""} usos</small></span><div><b>{p.discount_type==="percentage"?`${p.discount_value}%`:money(p.discount_value)}</b><button onClick={async()=>{await CutinService.updatePromotion(id,p.id,{active:!p.active});load()}}>{p.active?"Pausar":"Ativar"}</button></div></div>)}</div></div>}
 {tab==="vendas"&&<div className="panel"><h3>Vendas recentes</h3><table><thead><tr><th>Cliente</th><th>Status</th><th>Forma</th><th>Total</th><th>Ação</th></tr></thead><tbody>{(d.recent_sales||[]).map(s=><tr key={s.id}><td>{s.buyer_name}<small>{s.buyer_email}</small></td><td><span className={`status ${s.payment_status}`}>{s.payment_status}</span></td><td>{s.payment_method}</td><td>{money(s.total)}</td><td>{s.payment_status==="pending"&&s.payment_method!=="pix"?<button onClick={async()=>{await CutinService.confirmPayment(id,s.id);load()}}>Confirmar manualmente</button>:"—"}</td></tr>)}</tbody></table></div>}</section></CutinLayout>
}

export function CheckinPage(){
 const[token,setToken]=useState("");const[result,setResult]=useState(null);const[error,setError]=useState("");const[scanning,setScanning]=useState(false);const videoRef=useRef(null);const streamRef=useRef(null);
 const validate=async value=>{if(!value)return;setError("");try{const clean=value.includes("/")?value.split("/").pop():value;setResult(await CutinService.checkin(clean));setToken("");setScanning(false)}catch(x){setResult(x?.response?.data||null);setError(apiError(x,"Ingresso inválido."))}};
 const submit=e=>{e.preventDefault();validate(token)};
 useEffect(()=>{if(!scanning)return;let cancelled=false;const start=async()=>{if(!window.BarcodeDetector){setError("Leitura automática de QR não é suportada neste navegador. Use o token manual.");setScanning(false);return}try{streamRef.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});if(videoRef.current){videoRef.current.srcObject=streamRef.current;await videoRef.current.play()}const detector=new window.BarcodeDetector({formats:["qr_code"]});const loop=async()=>{if(cancelled||!videoRef.current)return;try{const codes=await detector.detect(videoRef.current);if(codes?.[0]?.rawValue){await validate(codes[0].rawValue);return}}catch{}setTimeout(loop,500)};loop()}catch{setError("Não foi possível acessar a câmera.");setScanning(false)}};start();return()=>{cancelled=true;streamRef.current?.getTracks()?.forEach(t=>t.stop());streamRef.current=null}},[scanning]);
 return <CutinLayout><section className="cutin-section narrow"><span className="eyebrow">Operação de entrada</span><h1>Check-in</h1><p className="page-subtitle">Leia o QR do ingresso ou digite o token. A API impede reutilização do mesmo acesso.</p><div className="panel"><button className={scanning?"secondary":"primary"} onClick={()=>setScanning(v=>!v)}>{scanning?"Fechar câmera":"Ler QR com câmera"}</button>{scanning&&<div className="scanner"><video ref={videoRef} muted playsInline/></div>}<form onSubmit={submit}><Field label="Token do ingresso" value={token} onChange={e=>setToken(e.target.value.trim())} placeholder="Cole o token do ingresso" required/><button className="secondary">Validar token</button></form>{result&&<div className={result.valid?"success-box":"error-box"}><strong>{result.message}</strong><p>{result.admission?.holder_name}</p></div>}{error&&<p className="error-text">{error}</p>}</div></section></CutinLayout>
}
