import React,{useEffect,useState}from"react";
import{Link,useParams}from"react-router-dom";
import CutinLayout from"../components/CutinLayout";
import CutinService from"../services/CutinService";
import"./CutinPages.css";

const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));
const msg=e=>e?.response?.data?.message||e?.response?.data?.error||Object.values(e?.response?.data?.errors||{}).flat()[0]||"Não foi possível concluir a operação.";
const blank={name:"",description:"",price:"",stock:"",category:"",status:true,is_featured:false};

export default function CutinProductsPage(){
 const{eventId}=useParams();const[items,setItems]=useState([]);const[form,setForm]=useState(blank);const[editing,setEditing]=useState(null);const[error,setError]=useState("");
 const load=()=>CutinService.eventProducts(eventId).then(v=>setItems(Array.isArray(v)?v:[])).catch(e=>setError(msg(e)));
 useEffect(()=>{load()},[eventId]);
 const change=e=>{const{name,type,value,checked}=e.target;setForm(v=>({...v,[name]:type==="checkbox"?checked:value}))};
 const reset=()=>{setEditing(null);setForm(blank)};
 const submit=async e=>{e.preventDefault();setError("");const payload={name:form.name,description:form.description||null,price:Number(form.price),stock:form.stock===""?null:Number(form.stock),category:form.category||null,status:Boolean(form.status),is_featured:Boolean(form.is_featured)};try{if(editing)await CutinService.updateEventProduct(eventId,editing,payload);else await CutinService.createEventProduct(eventId,payload);reset();await load()}catch(x){setError(msg(x))}};
 const edit=i=>{setEditing(i.id);setForm({name:i.name||"",description:i.description||"",price:String(i.price??""),stock:i.stock===null?"":String(i.stock),category:i.category||"",status:Boolean(i.status),is_featured:Boolean(i.is_featured)});window.scrollTo({top:0,behavior:"smooth"})};
 return <CutinLayout><section className="cutin-section"><div className="section-head"><div><span className="eyebrow">Pré-venda & extras</span><h1>Produtos do evento</h1><p className="page-subtitle">Venda camisetas, copos, consumação, estacionamento, experiências e outros extras junto dos ingressos.</p></div><Link className="secondary" to={`/gerenciar/evento/${eventId}`}>Voltar à gestão</Link></div>{error&&<div className="error-box">{error}</div>}<div className="two-col"><div className="panel"><h3>{editing?"Editar produto":"Novo produto"}</h3><form className="form-grid" onSubmit={submit}><input name="name" value={form.name} onChange={change} placeholder="Nome do produto" required/><input name="category" value={form.category} onChange={change} placeholder="Categoria: merchandising, consumação..."/><input name="price" value={form.price} onChange={change} type="number" min="0" step="0.01" placeholder="Preço" required/><input name="stock" value={form.stock} onChange={change} type="number" min="0" step="1" placeholder="Estoque (vazio = ilimitado)"/><textarea name="description" value={form.description} onChange={change} rows="5" placeholder="Descrição, regras de retirada ou uso"/><label className="check-row"><input name="status" type="checkbox" checked={form.status} onChange={change}/><span>Disponível para venda</span></label><label className="check-row"><input name="is_featured" type="checkbox" checked={form.is_featured} onChange={change}/><span>Destacar no evento</span></label><div className="inline-actions"><button className="primary">{editing?"Salvar produto":"Criar produto"}</button>{editing&&<button className="secondary" type="button" onClick={reset}>Cancelar</button>}</div></form></div><div className="panel"><h3>Catálogo do evento</h3>{items.length?items.map(i=><div className="lot-row" key={i.id}><div><strong>{i.name}</strong><small>{money(i.price)} · {i.stock===null?"estoque ilimitado":`${i.stock} em estoque`} · {i.status?"ativo":"pausado"}</small><small>{i.category||"Sem categoria"}</small></div><div className="inline-actions"><button onClick={()=>edit(i)}>Editar</button><button className="danger-button" onClick={async()=>{if(!window.confirm(`Excluir ${i.name}?`))return;try{await CutinService.deleteEventProduct(eventId,i.id);load()}catch(x){setError(msg(x))}}}>Excluir</button></div></div>):<p className="muted">Nenhum produto cadastrado.</p>}</div></div></section></CutinLayout>
}
