import React,{useEffect,useState}from"react";
import PropTypes from"prop-types";
import{Link}from"react-router-dom";
import{QRCodeSVG}from"qrcode.react";
import CutinLayout from"../components/CutinLayout";
import CutinService from"../services/CutinService";
import"./CutinPages.css";

const Page=({title,subtitle,children})=><CutinLayout><section className="cutin-section"><span className="eyebrow">Cutinapp</span><h1 className="page-title">{title}</h1><p className="page-subtitle">{subtitle}</p>{children}</section></CutinLayout>;
Page.propTypes={title:PropTypes.string.isRequired,subtitle:PropTypes.string.isRequired,children:PropTypes.node.isRequired};
const date=v=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";

export function EventsHubPage(){const[events,setEvents]=useState([]);const[city,setCity]=useState("");const[q,setQ]=useState("");useEffect(()=>{const t=setTimeout(()=>CutinService.events({...(city?{city}:{}),...(q?{q}:{})}).then(v=>setEvents(Array.isArray(v)?v:[])).catch(()=>setEvents([])),250);return()=>clearTimeout(t)},[city,q]);return <Page title="Eventos" subtitle="Descubra o que está acontecendo e encontre a próxima experiência para viver."><div className="panel form-grid two"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar evento, lugar ou experiência"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Cidade"/></div><div className="event-grid" style={{marginTop:18}}>{events.map((e,i)=><article className="event-card" key={e.id||i}><div className="event-cover" style={e.image?{backgroundImage:`url(${e.image})`}:undefined}><span>{e.city||"Evento"}</span></div><div className="event-body"><small>{date(e.start_date)}</small><h3>{e.title}</h3><p>{e.venue||e.description||"Confira detalhes, ingressos e produtos."}</p><Link to={`/evento/${e.id}`}>Ver evento</Link></div></article>)}</div>{!events.length&&<div className="empty-card">Nenhum evento encontrado com esses filtros.</div>}</Page>}

export function ProducerDashboardPage(){const[events,setEvents]=useState([]);useEffect(()=>{CutinService.myEvents().then(v=>setEvents(Array.isArray(v)?v:[])).catch(()=>setEvents([]))},[]);return <Page title="Central do produtor" subtitle="Publique eventos, configure lotes e produtos, organize equipe, acompanhe vendas e opere o acesso."><div className="hero-actions"><Link className="primary" to="/event/create">Criar evento</Link><Link className="secondary" to="/production/create">Cadastrar produção</Link><Link className="secondary" to="/checkin">Abrir check-in</Link></div><div className="panel"><h3>Meus eventos</h3>{events.length?<table><thead><tr><th>Evento</th><th>Data</th><th>Local</th><th></th></tr></thead><tbody>{events.map((e,i)=><tr key={e.id||i}><td><strong>{e.title||e.name}</strong></td><td>{date(e.start_date||e.start_at)}</td><td>{e.venue||e.city||"—"}</td><td><div className="inline-actions"><Link to={`/gerenciar/evento/${e.id}`}>Gerenciar</Link><Link to={`/gerenciar/evento/${e.id}/comissoes`}>Comissões</Link></div></td></tr>)}</tbody></table>:<p className="muted">Nenhum evento encontrado. Cadastre sua produção e publique o primeiro evento.</p>}</div></Page>}

export function TicketsPage(){const[tickets,setTickets]=useState([]);const[loading,setLoading]=useState(true);useEffect(()=>{CutinService.myTickets().then(v=>setTickets(Array.isArray(v)?v:[])).catch(()=>setTickets([])).finally(()=>setLoading(false))},[]);return <Page title="Meus ingressos" subtitle="Cada ingresso possui um QR único e só pode ser validado uma vez na entrada.">{loading?<div className="empty-card">Carregando ingressos...</div>:<div className="ticket-grid">{tickets.length?tickets.map((t,i)=><article className="ticket-card" key={t.id||i}><div className="row-between compact"><span className={`status ${t.status}`}>{t.status}</span><small>{t.sale_public_id}</small></div><h3>{t.event_title||"Ingresso"}</h3><p>{date(t.start_date)} · {t.venue||t.city||""}</p><div className="ticket-qr"><QRCodeSVG value={t.token||""} size={180} level="M" includeMargin/><small>Apresente este QR na entrada</small></div><div className="ticket-token"><small>Token</small><code>{t.token}</code></div><p>Participante: <strong>{t.holder_name}</strong></p></article>):<div className="empty-card">Você ainda não possui ingressos.</div>}</div>}</Page>}

export function MarketplacePage(){return <Page title="Produtos & experiências" subtitle="A Cutinapp permite que cada evento venda extras no mesmo pedido dos ingressos."><div className="feature-grid"><article><b>Pré-venda</b><h3>Produtos do evento</h3><p>Camisetas, copos, kits, estacionamento, consumação e merchandising.</p></article><article><b>Experiências</b><h3>Upsell no checkout</h3><p>Área VIP, meet & greet, mesas, combos e experiências adicionais.</p></article><article><b>Operação</b><h3>Estoque integrado</h3><p>O estoque é validado pelo backend e baixado somente quando a venda é confirmada.</p></article></div><p className="muted center">Os produtos aparecem dentro da página de cada evento.</p></Page>}

export function TeamPage(){const[events,setEvents]=useState([]);useEffect(()=>{CutinService.myEvents().then(v=>setEvents(Array.isArray(v)?v:[])).catch(()=>setEvents([]))},[]);return <Page title="Equipe & parceiros" subtitle="Promoters, fornecedores, colaboradores, gerentes e operadores de check-in são vinculados a cada evento."><div className="panel"><h3>Escolha um evento para administrar a equipe</h3>{events.map(e=><div className="row-between" key={e.id}><span><b>{e.title}</b><small>{e.city||e.venue||""}</small></span><div className="inline-actions"><Link to={`/gerenciar/evento/${e.id}`}>Abrir gestão</Link><Link to={`/gerenciar/evento/${e.id}/comissoes`}>Comissões</Link></div></div>)}</div></Page>}
