import React,{useEffect,useMemo,useState}from"react";
import{Link,useParams}from"react-router-dom";
import CutinLayout from"../components/CutinLayout";
import CutinService from"../services/CutinService";
import"./CutinPages.css";

const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));
const date=v=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const Field=({label,...props})=><label className="cutin-field"><span>{label}</span><input {...props}/></label>;

export function PublicEventPage(){
 const{id}=useParams();const[payload,setPayload]=useState(null);const[error,setError]=useState("");const[cart,setCart]=useState({});const[form,setForm]=useState({buyer_name:"",buyer_email:"",buyer_phone:"",payment_method:"pix",promoter_code:new URLSearchParams(window.location.search).get("ref")||"",promotion_code:""});const[result,setResult]=useState(null);
 useEffect(()=>{CutinService.publicEvent(id).then(setPayload).catch(e=>setError(e?.response?.data?.message||"Evento não encontrado."))},[id]);
 const lines=useMemo(()=>{if(!payload)return[];const all=[...(payload.tickets||[]).map(x=>({...x,type:"ticket"})),...(payload.products||[]).map(x=>({...x,type:"product"}))];return all.filter(x=>(cart[`${x.type}-${x.id}`]||0)>0).map(x=>({...x,quantity:cart[`${x.type}-${x.id}`]}))},[payload,cart]);
 const subtotal=lines.reduce((s,x)=>s+Number(x.price||0)*x.quantity,0);
 const add=(type,id,d=1)=>setCart(c=>({...c,[`${type}-${id}`]:Math.max(0,(c[`${type}-${id}`]||0)+d)}));
 const checkout=async e=>{e.preventDefault();setError("");try{const r=await CutinService.checkout(id,{...form,items:lines.map(x=>({type:x.type,id:x.id,quantity:x.quantity}))});setResult(r)}catch(err){setError(err?.response?.data?.message||Object.values(err?.response?.data?.errors||{})?.flat()?.[0]||"Não foi possível concluir a compra.")}};
 if(error&&!payload)return <CutinLayout><section className="cutin-section"><div className="empty-card">{error}</div></section></CutinLayout>;
 if(!payload)return <CutinLayout><section className="cutin-section"><div className="empty-card">Carregando evento...</div></section></CutinLayout>;
 const e=payload.event;
 return <CutinLayout><section className="cutin-section"><div className="event-detail-hero"><div><span className="eyebrow">{e.city||"Evento"}</span><h1>{e.title}</h1><p>{e.description}</p><div className="event-meta"><span>{date(e.start_date)}</span><span>{e.venue||e.address}</span></div></div></div>
 <div className="two-col"><div><h2>Ingressos</h2><div className="stack">{(payload.tickets||[]).map(t=><article className="panel" key={t.id}><div className="row-between"><div><strong>{t.name}</strong><p>{t.description}</p></div><b>{money(t.price)}</b></div><div className="qty"><button onClick={()=>add("ticket",t.id,-1)}>−</button><span>{cart[`ticket-${t.id}`]||0}</span><button onClick={()=>add("ticket",t.id,1)}>+</button></div></article>)}</div><h2>Produtos & extras</h2><div className="stack">{(payload.products||[]).map(p=><article className="panel" key={p.id}><div className="row-between"><div><strong>{p.name}</strong><p>{p.description}</p></div><b>{money(p.price)}</b></div><div className="qty"><button onClick={()=>add("product",p.id,-1)}>−</button><span>{cart[`product-${p.id}`]||0}</span><button onClick={()=>add("product",p.id,1)}>+</button></div></article>)}</div></div>
 <aside className="panel checkout-box"><h2>Seu pedido</h2>{lines.length?lines.map(x=><div className="row-between" key={`${x.type}-${x.id}`}><span>{x.quantity}× {x.name}</span><b>{money(Number(x.price)*x.quantity)}</b></div>):<p>Nenhum item selecionado.</p>}<hr/><div className="row-between"><strong>Subtotal</strong><strong>{money(subtotal)}</strong></div>{result?<div className="success-box"><strong>{result.message}</strong><p>Pedido: {result.sale?.public_id}</p><Link to="/meus-ingressos">Ver meus ingressos</Link></div>:<form onSubmit={checkout}><Field label="Nome" value={form.buyer_name} onChange={x=>setForm({...form,buyer_name:x.target.value})} required/><Field label="E-mail" type="email" value={form.buyer_email} onChange={x=>setForm({...form,buyer_email:x.target.value})} required/><Field label="Telefone" value={form.buyer_phone} onChange={x=>setForm({...form,buyer_phone:x.target.value})}/><Field label="Cupom" value={form.promotion_code} onChange={x=>setForm({...form,promotion_code:x.target.value.toUpperCase()})}/><Field label="Código do promoter" value={form.promoter_code} onChange={x=>setForm({...form,promoter_code:x.target.value.toUpperCase()})}/><label className="cutin-field"><span>Pagamento</span><select value={form.payment_method} onChange={x=>setForm({...form,payment_method:x.target.value})}><option value="pix">PIX</option><option value="credit_card">Cartão de crédito</option><option value="debit_card">Cartão de débito</option></select></label>{error&&<p className="error-text">{error}</p>}<button className="primary" disabled={!lines.length}>Finalizar pedido</button></form>}</aside></div></section></CutinLayout>
}

export function EventManagePage(){
 const{id}=useParams();const[d,setD]=useState(null);const[members,setMembers]=useState([]);const[promoters,setPromoters]=useState([]);const[promotions,setPromotions]=useState([]);const[tab,setTab]=useState("dashboard");const[msg,setMsg]=useState("");
 const load=()=>Promise.all([CutinService.dashboard(id),CutinService.members(id),CutinService.promoters(id),CutinService.promotions(id)]).then(([a,b,c,p])=>{setD(a);setMembers(Array.isArray(b)?b:[]);setPromoters(Array.isArray(c)?c:[]);setPromotions(Array.isArray(p)?p:[])}).catch(e=>setMsg(e?.response?.data?.message||"Não foi possível carregar a gestão."));
 useEffect(()=>{load()},[id]);
 const addMember=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await CutinService.createMember(id,Object.fromEntries(f));e.currentTarget.reset();load()};
 const addPromo=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await CutinService.createPromotion(id,{...Object.fromEntries(f),discount_value:Number(f.get("discount_value"))});e.currentTarget.reset();load()};
 const addPromoter=async memberId=>{await CutinService.createPromoter(id,{member_id:memberId,commission_type:"percentage",commission_value:10});load()};
 if(!d)return <CutinLayout><section className="cutin-section"><div className="empty-card">{msg||"Carregando gestão..."}</div></section></CutinLayout>;
 const m=d.metrics||{};
 return <CutinLayout><section className="cutin-section"><div className="section-head"><div><span className="eyebrow">Gestão do evento</span><h1>{d.event?.title}</h1></div><Link className="primary" to={`/evento/${id}`}>Ver página pública</Link></div><div className="tabs">{["dashboard","equipe","promoters","promocoes","vendas"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
 {tab==="dashboard"&&<><div className="dashboard-grid"><div className="metric"><span>Vendas</span><strong>{m.sales_count||0}</strong></div><div className="metric"><span>Receita</span><strong>{money(m.revenue)}</strong></div><div className="metric"><span>Ingressos</span><strong>{m.tickets_issued||0}</strong></div><div className="metric"><span>Check-ins</span><strong>{m.checkins||0}</strong></div><div className="metric"><span>Comissões</span><strong>{money(m.commissions)}</strong></div><div className="metric"><span>Equipe</span><strong>{m.members||0}</strong></div></div><div className="panel"><h3>Ranking de promoters</h3>{(d.promoter_ranking||[]).map(p=><div className="row-between" key={p.id}><span>{p.code} · {p.sales_count} vendas</span><b>{money(p.revenue)} · {money(p.commissions)} comissão</b></div>)}</div></>}
 {tab==="equipe"&&<div className="two-col"><div className="panel"><h3>Adicionar pessoa</h3><form onSubmit={addMember} className="form-grid"><input name="name" placeholder="Nome" required/><input name="email" type="email" placeholder="E-mail"/><input name="phone" placeholder="Telefone"/><select name="role" defaultValue="collaborator"><option value="manager">Gerente</option><option value="promoter">Promoter</option><option value="supplier">Fornecedor</option><option value="collaborator">Colaborador</option><option value="checker">Check-in</option></select><button className="primary">Adicionar</button></form></div><div className="panel"><h3>Equipe atual</h3>{members.map(x=><div className="row-between" key={x.id}><span><b>{x.name}</b><small>{x.role} · {x.status}</small></span>{x.role==="promoter"&&!promoters.some(p=>p.member_id===x.id)&&<button onClick={()=>addPromoter(x.id)}>Ativar comissão</button>}</div>)}</div></div>}
 {tab==="promoters"&&<div className="panel"><h3>Promoters e links</h3>{promoters.map(p=><div className="row-between" key={p.id}><span><b>{p.name||p.code}</b><small>{p.code} · {p.commission_value}%</small></span><button onClick={()=>navigator.clipboard?.writeText(`${window.location.origin}/evento/${id}?ref=${p.code}`)}>Copiar link</button></div>)}</div>}
 {tab==="promocoes"&&<div className="two-col"><div className="panel"><h3>Criar promoção</h3><form onSubmit={addPromo} className="form-grid"><input name="name" placeholder="Nome da promoção" required/><input name="code" placeholder="Cupom"/><select name="discount_type"><option value="percentage">Percentual</option><option value="fixed">Valor fixo</option></select><input name="discount_value" type="number" step="0.01" min="0" placeholder="Desconto" required/><button className="primary">Criar promoção</button></form></div><div className="panel"><h3>Promoções</h3>{promotions.map(p=><div className="row-between" key={p.id}><span>{p.name} · {p.code||"sem cupom"}</span><b>{p.discount_type==="percentage"?`${p.discount_value}%`:money(p.discount_value)}</b></div>)}</div></div>}
 {tab==="vendas"&&<div className="panel"><h3>Vendas recentes</h3><table><thead><tr><th>Cliente</th><th>Status</th><th>Total</th><th>Ação</th></tr></thead><tbody>{(d.recent_sales||[]).map(s=><tr key={s.id}><td>{s.buyer_name}<small>{s.buyer_email}</small></td><td>{s.payment_status}</td><td>{money(s.total)}</td><td>{s.payment_status==="pending"?<button onClick={async()=>{await CutinService.confirmPayment(id,s.id);load()}}>Confirmar pagamento</button>:"—"}</td></tr>)}</tbody></table></div>}</section></CutinLayout>
}

export function CheckinPage(){const[token,setToken]=useState("");const[result,setResult]=useState(null);const[error,setError]=useState("");const submit=async e=>{e.preventDefault();setError("");try{setResult(await CutinService.checkin(token));setToken("")}catch(x){setResult(x?.response?.data||null);setError(x?.response?.data?.message||"Ingresso inválido.")}};return <CutinLayout><section className="cutin-section narrow"><span className="eyebrow">Operação de entrada</span><h1>Check-in</h1><div className="panel"><form onSubmit={submit}><Field label="Token do ingresso" value={token} onChange={e=>setToken(e.target.value.trim())} placeholder="Leia o QR ou cole o token" required/><button className="primary">Validar ingresso</button></form>{result&&<div className={result.valid?"success-box":"error-box"}><strong>{result.message}</strong><p>{result.admission?.holder_name}</p></div>}{error&&<p className="error-text">{error}</p>}</div></section></CutinLayout>}
