import { canNavigate } from "./capabilityResolver";
export const PRODUCTION_STORAGE_KEY="cutinapp:navigation-production"; export const NAV_USAGE_STORAGE_KEY="cutinapp:navigation-usage";
const item=(id,label,icon,to,extras={})=>({id,label,icon,to,...extras});
export const commonNavigation=[item("events","Eventos","fa-regular fa-calendar-days","/event"),item("feed","Feed","fa-solid fa-bolt","/feed"),item("productions","Produções","fa-solid fa-building","/productions"),item("artists","Artistas","fa-solid fa-music","/artists")];
export const accountNavigation=[item("profile","Meu perfil","fa-regular fa-user","/profile"),item("passes","Meus ingressos","fa-solid fa-ticket","/passes"),item("purchases","Minhas compras","fa-solid fa-receipt","/purchases"),item("notifications","Notificações","fa-regular fa-bell","/notifications"),item("dashboard","Meu painel","fa-solid fa-gauge-high","/dashboard"),item("account-settings","Editar conta","fa-solid fa-gear","/user/edit"),item("password","Alterar senha","fa-solid fa-key","/password")];
export const actorNavigation=[
{id:"producer",label:"Produção",icon:"fa-solid fa-briefcase",requirement:"producer",description:"Gestão, receita e operação",groups:[
{label:"Gestão",items:[item("my-productions","Minhas produções","fa-solid fa-building","/production/mine",{requirement:"production.manage"}),item("manage-events","Meus eventos","fa-solid fa-calendar-check","/event/manage",{requirement:"event.manage"}),item("create-event","Criar evento","fa-solid fa-calendar-plus","/event/create",{requirement:"event.manage"}),item("contracts","Contratos","fa-solid fa-file-signature","/producer/contracts",{requirement:"production.manage"})]},
{label:"Receita",items:[item("create-ticket","Ingressos e cortesias","fa-solid fa-ticket","/ticket/create",{requirement:"ticket.manage"}),item("sales","Vendas","fa-solid fa-chart-line","/producer/sales",{requirement:"sales.view"}),item("finance","Financeiro","fa-solid fa-wallet","/producer/finance",{requirement:"finance.view"})]},
{label:"Operação",items:[item("checkin","Portaria / check-in","fa-solid fa-qrcode","/checkin",{requirement:"checkin.manage"})]}],quick:[item("quick-create-event","Criar evento","fa-solid fa-calendar-plus","/event/create",{requirement:"event.manage"}),item("quick-create-ticket","Criar ingresso","fa-solid fa-ticket","/ticket/create",{requirement:"ticket.manage"}),item("quick-checkin","Abrir check-in","fa-solid fa-qrcode","/checkin",{requirement:"checkin.manage"}),item("quick-sales","Ver vendas","fa-solid fa-chart-line","/producer/sales",{requirement:"sales.view"})]},
{id:"artist",label:"Artista",icon:"fa-solid fa-music",requirement:"artist",description:"Carreira, agenda e eventos",items:[item("artist-area","Área do artista","fa-solid fa-microphone-lines","/artist/manage",{requirement:"artist.manage"}),item("artist-events","Explorar eventos","fa-regular fa-calendar-days","/event"),item("artist-discovery","Explorar artistas","fa-solid fa-users","/artists")],quick:[item("quick-artist","Gerenciar carreira","fa-solid fa-wand-magic-sparkles","/artist/manage",{requirement:"artist.manage"})]},
{id:"promoter",label:"Promoter",icon:"fa-solid fa-bullhorn",requirement:"promoter",description:"Divulgação, atribuição e comissão",items:[item("promoter-events","Eventos para divulgar","fa-regular fa-calendar-days","/event"),item("promoter-sales","Vendas atribuídas","fa-solid fa-chart-line","/producer/sales",{requirement:"sales.view"}),item("promoter-feed","Feed","fa-solid fa-bolt","/feed")],quick:[item("quick-promoter","Encontrar evento","fa-solid fa-bullhorn","/event",{requirement:"promoter.manage"})]},
{id:"agent",label:"Agente",icon:"fa-solid fa-user-tie",requirement:"agent",description:"Aquisição e relacionamento",items:[item("agent-dashboard","Painel do agente","fa-solid fa-gauge","/agent")]},
{id:"admin",label:"Administração",icon:"fa-solid fa-shield-halved",requirement:"admin",description:"Operação e governança",items:[item("admin-center","Admin Center","fa-solid fa-shield-halved","/admin",{requirement:"application.admin"}),item("admin-users","Usuários","fa-solid fa-users-gear","/admin/users",{requirement:"application.admin"}),item("admin-events","Eventos","fa-solid fa-calendar-days","/admin/events",{requirement:"application.admin"}),item("moderation","Moderação","fa-solid fa-user-shield","/moderation/reports",{requirement:"application.admin"})]}
];
const flatten=(area)=>area.groups?.flatMap((group)=>group.items)||area.items||[];
export const actorMenusFor=(capabilities)=>actorNavigation.filter((area)=>canNavigate(capabilities,area.requirement)).map((area)=>({...area,groups:area.groups?.map((group)=>({...group,items:group.items.filter((entry)=>canNavigate(capabilities,entry.requirement))})).filter((group)=>group.items.length),items:flatten(area).filter((entry)=>canNavigate(capabilities,entry.requirement))}));
export const quickActionsFor=(capabilities)=>actorMenusFor(capabilities).flatMap((area)=>area.quick||[]).filter((entry,index,all)=>canNavigate(capabilities,entry.requirement)&&all.findIndex((candidate)=>candidate.to===entry.to)===index);
export const contextualNavigation=(pathname="",capabilities={})=>{const event=pathname.match(/^\/event\/(?:edit\/)?(?!create|manage)([^/]+)/);if(event&&capabilities.producer)return{label:"Evento atual",items:[item("event-view","Ver evento","fa-regular fa-eye",`/event/${event[1]}`),item("event-edit","Editar evento","fa-solid fa-pen",`/event/edit/${event[1]}`),item("event-courtesies","Cortesias","fa-solid fa-gift",`/event/${event[1]}/courtesies`),item("event-participants","Participantes","fa-solid fa-users",`/event/${event[1]}/participants`),item("event-lineup","Line-up","fa-solid fa-music",`/event/${event[1]}/lineup`),item("event-checkin","Check-in","fa-solid fa-qrcode","/checkin")]};const production=pathname.match(/^\/production\/(?:edit\/)?(\d+)/);if(production&&capabilities.producer)return{label:"Produção atual",items:[item("production-view","Visão geral","fa-solid fa-building",`/production/${production[1]}`),item("production-edit","Editar produção","fa-solid fa-pen",`/production/edit/${production[1]}`),item("production-agenda","Agenda","fa-regular fa-calendar",`/production/${production[1]}/agenda`),item("production-new-event","Novo evento","fa-solid fa-calendar-plus","/event/create"),item("production-sales","Vendas","fa-solid fa-chart-line","/producer/sales")]};return null;};
export const readNavigationUsage=(raw)=>{if(!raw)return{};try{const parsed=JSON.parse(raw);return parsed&&typeof parsed==="object"?parsed:{}}catch(_){return{}}};
export const rankQuickActions=(actions,usage={})=>[...actions].sort((a,b)=>Number(usage[b.id]||0)-Number(usage[a.id]||0)||actions.indexOf(a)-actions.indexOf(b));
